 <div class="container-fluid text-center">
    <div class="row content">
        <div class="nav-side-menu">
            <div class="brand">DIRECTOR</div>
            <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
          
                <div class="menu-list">
          
                    <ul id="menu-content" class="menu-content collapse out">
                      
                        <li  data-toggle="collapse" data-target="#products" class="collapsed active">
                          <a href="#"><i class="glyphicon glyphicon-plus"></i> PERSONAL <span class="arrow"></span></a>
                        </li>
                        <ul class="sub-menu collapse" id="products">
                            <li class="active"><a href="../DIRECTOR/vistaContratar.php"><i class="glyphicon glyphicon-plus-sign"></i>Contratar empleados</a></li>
                            <li><a href="../DIRECTOR/vistaGestionEmpleados.php"><i class="glyphicon glyphicon-cog"></i>Consultar empleados</a></li>
                        </ul>
        
        
                        <li data-toggle="collapse" data-target="#service" class="collapsed">
                          <a href="#"><i class="glyphicon glyphicon-cog"></i> GESTIÓN <span class="arrow"></span></a>
                        </li>  
                        <ul class="sub-menu collapse" id="service">
                        <li class="active"><a href="../COMUN/vistaGestionCliente.php"><i class="glyphicon glyphicon-cog"></i>Gestionar clientes</a></li>
                            <li><a href="../COMUN/vistaGestionMascotas.php"><i class="glyphicon glyphicon-cog"></i>Gestionar mascotas</a></li>
                            <li><a href="../COMUN/vistaGestionPrueba.php"><i class="glyphicon glyphicon-list-alt"></i>Consultar pruebas</a></li>
                            <li><a href="../COMUN/vistaGestionCitas.php"><i class="glyphicon glyphicon-time"></i>Consultar citas</a></li>
                        </ul>

                    </ul>
             </div>
        </div>
        </div>
        </div>