 <div class="container-fluid text-center">
    <div class="row content late">
        <div class="nav-side-menu">
            <div class="brand">VETERINARIO</div>
            <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
          
                <div class="menu-list">
          
                    <ul id="menu-content" class="menu-content collapse out">

                        <li  data-toggle="collapse" data-target="#products" class="collapsed active">
                             <a href="#"><i class="glyphicon glyphicon-plus"></i> PRUEBA <span class="arrow"></span></a>
                        </li>
                        <ul class="sub-menu collapse" id="products">
                            <li><a href="../VETERINARIO/vistaAnadirTipoPrueba.php"><i class="glyphicon glyphicon-plus-sign"></i>Añadir Tipo de prueba</a></li>
                        </ul>

                        <li data-toggle="collapse" data-target="#service" class="collapsed">
                          <a href="#"><i class="glyphicon glyphicon-tint"></i> GESTIÓN <span class="arrow"></span></a>
                        </li>  
                        <ul class="sub-menu collapse" id="service">
                            <li><a href="../COMUN/vistaGestionCitas.php"><i class="glyphicon glyphicon-eye-open"></i>Consultar citas / Añadir pruebas </a></li>
                            <li><a href="../COMUN/vistaGestionCliente.php"><i class="glyphicon glyphicon-cog"></i>Consultar clientes</a></li>
                            <li><a href="../COMUN/vistaGestionMascotas.php"><i class="glyphicon glyphicon-cog"></i>Gestionar mascotas</a></li>
                            <li><a href="../COMUN/vistaGestionPrueba.php"><i class="glyphicon glyphicon-cog"></i>Gestionar pruebas</a></li>
                            <li><a href="../COMUN/vistaGestionTipoPrueba.php"><i class="glyphicon glyphicon-cog"></i>Gestionar tipo de pruebas</a></li>
                        </ul>

                    </ul>
             </div>
        </div>
        </div>
        </div>