 <div class="container-fluid text-center">
    <div class="row content">
        <div class="nav-side-menu">
            <div class="brand">RECEPCIÓN</div>
            <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
          
                <div class="menu-list">
          
                    <ul id="menu-content" class="menu-content collapse out">
        
                        <li  data-toggle="collapse" data-target="#products" class="collapsed active">
                          <a href="#"><i class="glyphicon glyphicon-user"></i>CLIENTES<span class="arrow"></span></a>
                        </li>
                        <ul class="sub-menu collapse" id="products">
                            <li class="active"><a href="../RECEPCIONISTA/vistaRegistroCliente.php"><i class="glyphicon glyphicon-plus-sign"></i>Añadir cliente</a></li>
                        </ul>

                        <li data-toggle="collapse" data-target="#service" class="collapsed">
                          <a href="#"><i class="glyphicon glyphicon-cog"></i>GESTIÓN<span class="arrow"></span></a>
                        </li>  
                        <ul class="sub-menu collapse" id="service">
                        <li><a href="../COMUN/vistaGestionCliente.php"><i class="glyphicon glyphicon-cog"></i>Gestión Clientes</a></li>
                           <li><a href="../COMUN/vistaGestionMascotas.php"><i class="glyphicon glyphicon-cog"></i>Gestión Mascotas</a></li>
                           <li class="active"><a href="../COMUN/vistaGestionCitas.php"><i class="glyphicon glyphicon-cog"></i>Gestionar citas</a></li>
                           <li class="active"><a href="../COMUN/vistaGestionCitas.php"><i class="glyphicon glyphicon-eye-open"></i>Consultar tipos de prueba</a></li>
                        </ul>

                    </ul>
             </div>
        </div>
        </div>
        </div>