 <div class="container-fluid text-center">
    <div class="row content">
        <div class="nav-side-menu">
            <div class="brand">RECEPCIÓN</div>
            <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
          
                <div class="menu-list">
          
                    <ul id="menu-content" class="menu-content collapse out">
        
                        <li  data-toggle="collapse" data-target="#products" class="collapsed active">
                          <a href="#"><i class="glyphicon glyphicon-user"></i>CLIENTES<span class="arrow"></span></a>
                        </li>
                        <ul class="sub-menu collapse" id="products">
                            <li class="active"><a href="#"><i class="glyphicon glyphicon-plus-sign"></i>Añadir cliente</a></li>
                            <li><a href="#"><i class="glyphicon glyphicon-plus-sign"></i>Añadir mascota</a></li>
                            <li><a href="#"><i class="glyphicon glyphicon-eye-open"></i>Consultar clientes/mascotas</a></li>
                            <li class="active"><a href="#"><i class="glyphicon glyphicon-plus-sign"></i>Añadir cita</a></li>
                            <li><a href="#"><i class="glyphicon glyphicon-eye-open"></i>Ver / modificar citas</a></li>  
                        </ul>

                        <li data-toggle="collapse" data-target="#service" class="collapsed">
                          <a href="#"><i class="glyphicon glyphicon-usd"></i>PAGO<span class="arrow"></span></a>
                        </li>  
                        <ul class="sub-menu collapse" id="service">
                            <li class="active"><a href="#"><i class="glyphicon glyphicon-plus-usd"></i>Realizar pago</a></li>
                            <li><a href="#"><i class="glyphicon glyphicon-eye-open"></i>Consultar pagos</a></li>  
                        </ul>

                    </ul>
             </div>
        </div>
        </div>
        </div>