 <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
      <img class="logotipo" src="../../IMAGENES/logotb.png" width="250px" height="auto" > 
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </nav>